### ISSUE TITLE
Error trying to build maven project from root folder

### ISSUE THREAD

**Issue by jamiecoleman92** [OpenLiberty/guide-kubernetes-microprofile-health#39]
When I try building the two applications via maven I get the following error:

```
[WARNING] Error injecting: net.wasdev.wlp.maven.plugins.server.InstallServerMojo
com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) Error injecting: private org.eclipse.aether.spi.log.Logger org.apache.maven.repository.internal.DefaultVersionRangeResolver.logger
  while locating org.apache.maven.repository.internal.DefaultVersionRangeResolver
  while locating java.lang.Object annotated with *
  at org.eclipse.sisu.wire.LocatorWiring
  while locating org.eclipse.aether.impl.VersionRangeResolver
    for parameter 2 at org.eclipse.aether.internal.impl.DefaultDependencyCollector.<init>(Unknown Source)
  while locating org.eclipse.aether.internal.impl.DefaultDependencyCollector
  while locating java.lang.Object annotated with *
  at org.eclipse.sisu.wire.LocatorWiring
  while locating org.eclipse.aether.impl.DependencyCollector
    for parameter 5 at org.eclipse.aether.internal.impl.DefaultRepositorySystem.<init>(Unknown Source)
  while locating org.eclipse.aether.internal.impl.DefaultRepositorySystem
  while locating java.lang.Object annotated with *
  while locating net.wasdev.wlp.maven.plugins.server.InstallServerMojo
Caused by: java.lang.IllegalArgumentException: Can not set org.eclipse.aether.spi.log.Logger field org.apache.maven.repository.internal.DefaultVersionRangeResolver.logger to org.eclipse.aether.internal.impl.slf4j.Slf4jLoggerFactory
    at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:167)
    at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:171)
    at sun.reflect.UnsafeObjectFieldAccessorImpl.set(UnsafeObjectFieldAccessorImpl.java:81)
    at java.lang.reflect.Field.set(Field.java:764)
    at org.eclipse.sisu.bean.BeanPropertyField.set(BeanPropertyField.java:72)
    at org.eclipse.sisu.plexus.ProvidedPropertyBinding.injectProperty(ProvidedPropertyBinding.java:48)
    at org.eclipse.sisu.bean.BeanInjector.injectMembers(BeanInjector.java:52)
    at com.google.inject.internal.MembersInjectorImpl.injectMembers(MembersInjectorImpl.java:140)
    at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:117)
    at com.google.inject.internal.ConstructorInjector.access$000(ConstructorInjector.java:32)
    at com.google.inject.internal.ConstructorInjector$1.call(ConstructorInjector.java:92)
```

If I go into the individual projects I do not get this error. 

If I build them from the `start` directory it builds the first Docker image then goes to do the second image build only to fail.

This only happens in certain enviroments as on my Linux VM it all works fine but in my online Katacoda enviroment it does not work. It also has not been working for some others in a mac enviroments.
@gcharters

**Comment by gcharters** [comment]
@proubatsis @gkwan-ibm - I've seen this is the two kubernetes guides I've tested, so if it's a guide bug it'll need fixing in multiple places (likely all the kube guides and maybe the istio guide).  

Also, I'll be using these guides for a conference workshop on Wednesday so if we can get a fix soon, that would be awesome.

Many thanks.

**Comment by gcharters** [comment]
I think this is the same problem, but I've just found that the following fails when run inside the ping directory: `mvn verify -Ddockerfile.skip=true -Dcluster.ip=localhost` . with

```
[ERROR] Failed to execute goal net.wasdev.wlp.maven.plugins:liberty-maven-plugin:2.6.4:test-start-server (test-start-server) on project ping: Execution test-start-server of goal net.wasdev.wlp.maven.plugins:liberty-maven-plugin:2.6.4:test-start-server failed: Unable to load the mojo 'test-start-server' (or one of its required components) from the plugin 'net.wasdev.wlp.maven.plugins:liberty-maven-plugin:2.6.4': com.google.inject.ProvisionException: Unable to provision, see the following errors:
[ERROR] 
[ERROR] 1) Error injecting: private org.eclipse.aether.spi.log.Logger org.apache.maven.repository.internal.DefaultVersionRangeResolver.logger
[ERROR] while locating org.apache.maven.repository.internal.DefaultVersionRangeResolver
[ERROR] while locating java.lang.Object annotated with *
[ERROR] at org.eclipse.sisu.wire.LocatorWiring
[ERROR] while locating org.eclipse.aether.impl.VersionRangeResolver
[ERROR] for parameter 2 at org.eclipse.aether.internal.impl.DefaultDependencyCollector.<init>(Unknown Source)
[ERROR] while locating org.eclipse.aether.internal.impl.DefaultDependencyCollector
[ERROR] while locating java.lang.Object annotated with *
[ERROR] at org.eclipse.sisu.wire.LocatorWiring

```

**Comment by gkwan-ibm** [comment]
@jamiecoleman92 I am closing this issue. If you still have issue by using Maven 3.6.0 or above, you may reopen this issue. Thank you!
